### ISSUE TITLE
GET on async handler fails

### ISSUE THREAD

**Issue by serialseb** [openrasta/openrasta-core#108]
Reported by @nmosafi, test added in #107 

> One particular scenario which fails is when an Task based method is handling a request and the handler takes a dependency. This would need to be resolved before merging to the master branch

Exception:
```
System.MissingMethodException: No parameterless constructor defined for this object.
         at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
         at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
         at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
         at System.Activator.CreateInstance(Type type, Boolean nonPublic)
         at System.Activator.CreateInstance(Type type)
         at OpenRasta.TypeSystem.ReflectionBased.ReflectionExtensions.CreateInstance(Type type) in C:\projects\openrasta-core\src\OpenRasta\TypeSystem\ReflectionBased\ReflectionExtensions.cs:line 64
         at OpenRasta.TypeSystem.ReflectionBased.ReflectionBasedType.CreateInstance() in C:\projects\openrasta-core\src\OpenRasta\TypeSystem\ReflectionBased\ReflectionBasedType.cs:line 69
         at OpenRasta.OperationModel.MethodBased.AbstractMethodOperation.CreateInstance(IType type, IDependencyResolver resolver) in C:\projects\openrasta-core\src\OpenRasta\OperationModel\MethodBased\AbstractMethodOperation.cs:line 62
         at OpenRasta.OperationModel.MethodBased.AsyncMethod`1.<InvokeAsync>d__4.MoveNext() in C:\projects\openrasta-core\src\OpenRasta\OperationModel\MethodBased\MethodBasedOperation.cs:line 0
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at OpenRasta.OperationModel.OperationExecutor.<Execute>d__0.MoveNext() in C:\projects\openrasta-core\src\OpenRasta\OperationModel\OperationExecutor.cs:line 13
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at OpenRasta.Pipeline.Contributors.OperationInvokerContributor.<ExecuteOperations>d__3.MoveNext() in C:\projects\openrasta-core\src\OpenRasta\Pipeline\Contributors\OperationInvokerContributor.cs:line 30
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at OpenRasta.Pipeline.RequestMiddleware.<Invoke>d__1.MoveNext() in C:\projects\openrasta-core\src\OpenRasta\Pipeline\RequestMiddleware.cs:line 27
```

**Comment by serialseb** [comment]
Fixed in 6d21b68231ab1fdfa2b73cc461ac49dc37375a1b
