### ISSUE TITLE
Race condition (concurrency issue) in SurrogateBuilderProvider

### ISSUE THREAD

**Issue by JornWildt** [openrasta/openrasta-core#86]
The code here has a race condition problem:

```
        T Cached<T>(Dictionary<T, T> cache, T value, Func<T, T> createCached)
        {
            T cachedValue;
            if (cache.TryGetValue(value, out cachedValue))
                return cachedValue;
            lock (cache)
            {
                cachedValue = createCached(value);
                cache.Add(value, cachedValue);
                return cachedValue;
            }
        }
```

The TryGetValue should be inside the lock(...) statement - otherwise two different threads may see that the same item is missing and then try to insert one after another leading to a "System.ArgumentException: An item with the same key has already been added.".

The stacktrace here is from two identical requests executed simultaneous:

DEBUG 2015-08-11 13:53:44,161  1968ms  [48] Log4NetTraceListener   WriteLine          - Incoming host request for http://jw-pc261.cbrain.net/f2-restservices-5.0/distributed-requisitions/747/accept
DEBUG 2015-08-11 13:53:44,165  1972ms  [48] Log4NetTraceListener   WriteLine          - Entering OpenRastaRewriterHandler: Rewriting to original path
DEBUG 2015-08-11 13:53:44,167  1974ms  [48] Log4NetTraceListener   WriteLine          - Entering OpenRastaIntegratedHandler: Request for http://jw-pc261.cbrain.net/f2-restservices-5.0/distributed-requisitions/747/accept
DEBUG 2015-08-11 13:53:44,169  1976ms  [48] Log4NetTraceListener   WriteLine          - Incoming host request for http://jw-pc261.cbrain.net/f2-restservices-5.0/distributed-requisitions/747/accept
DEBUG 2015-08-11 13:53:44,170  1977ms  [57] Log4NetTraceListener   WriteLine          - Incoming host request for http://jw-pc261.cbrain.net/f2-restservices-5.0/distributed-requisitions/747/accept
DEBUG 2015-08-11 13:53:44,173  1980ms  [57] Log4NetTraceListener   WriteLine          - Entering OpenRastaRewriterHandler: Rewriting to original path
DEBUG 2015-08-11 13:53:44,174  1981ms  [57] Log4NetTraceListener   WriteLine          - Entering OpenRastaIntegratedHandler: Request for http://jw-pc261.cbrain.net/f2-restservices-5.0/distributed-requisitions/747/accept
DEBUG 2015-08-11 13:53:44,175  1982ms  [57] Log4NetTraceListener   WriteLine          - Incoming host request for http://jw-pc261.cbrain.net/f2-restservices-5.0/distributed-requisitions/747/accept
DEBUG 2015-08-11 13:53:44,189  1996ms  [48] Log4NetTraceListener   WriteLine          - Operation AcceptRequisitionHandler::Post(Int64 id, AcceptRequisitionArgs args) selected with 2 required members and 0 optional members, with codec ApplicationXWwwFormUrlencodedKeyedValuesCodec with score 2.5.
DEBUG 2015-08-11 13:53:44,191  1998ms  [57] Log4NetTraceListener   WriteLine          - Operation AcceptRequisitionHandler::Post(Int64 id, AcceptRequisitionArgs args) selected with 2 required members and 0 optional members, with codec ApplicationXWwwFormUrlencodedKeyedValuesCodec with score 2.5.
DEBUG 2015-08-11 13:53:44,224  2031ms  [57] enAuthorizationHandler IsAuthorized       - Check Bearer authorization
DEBUG 2015-08-11 13:53:44,227  2034ms  [57] enAuthorizationHandler IsAuthorized       - Got authorization header.
DEBUG 2015-08-11 13:53:44,229  2036ms  [57] icAuthorizationHandler IsAuthorized       - Check Basic authorization
DEBUG 2015-08-11 13:53:44,231  2038ms  [57] icAuthorizationHandler GetUsernamePassword - Got authorization header.
DEBUG 2015-08-11 13:53:44,230  2037ms  [48] Log4NetTraceListener   Write              - openrasta Error: 0 : 
DEBUG 2015-08-11 13:53:44,236  2043ms  [48] Log4NetTraceListener   WriteLine          - An error has occurred and the processing of the request has stopped.

Exception:
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OpenRasta.TypeSystem.Surrogated.SurrogateBuilderProvider.Cached[T](Dictionary`2 cache, T value, Func`2 createCached) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\TypeSystem\Surrogated\SurrogateBuilderProvider.cs:line 67
   at OpenRasta.TypeSystem.Surrogated.SurrogateBuilderProvider.FindPropertySurrogate(IProperty property) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\TypeSystem\Surrogated\SurrogateBuilderProvider.cs:line 39
   at OpenRasta.TypeSystem.Surrogated.SurrogateBuilderProvider.FindSurrogate[T](T member) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\TypeSystem\Surrogated\SurrogateBuilderProvider.cs:line 32
   at OpenRasta.TypeSystem.PropertyExtensions.FindPropertyByPath(IMember source, String propertyName) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\TypeSystem\PropertyExtensions.cs:line 21
   at OpenRasta.TypeSystem.MemberBuilder.GetProperty(String propertyPath) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\TypeSystem\MemberBuilder.cs:line 38
   at OpenRasta.Binding.KeyedValuesBinder.SetPropertyValue[TValue](String key, String property, IEnumerable`1 values, ValueConverter`1 converter) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Binding\KeyedValuesBinder.cs:line 96
   at OpenRasta.Binding.KeyedValuesBinder.SetProperty[TValue](String key, IEnumerable`1 values, ValueConverter`1 converter) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Binding\KeyedValuesBinder.cs:line 80
   at OpenRasta.Binding.KeyedValues`1.SetProperty(IObjectBinder binder) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Binding\KeyedValues`1.cs:line 37
   at OpenRasta.Codecs.CodecExtensions.<>c__DisplayClass8.<TryAssignKeyValues>b__7(KeyedValues kv) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Codecs\CodecExtensions.cs:line 38
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at OpenRasta.Collections.ObservableIterator`1.<GetEnumerator>d__0.MoveNext() in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Collections\ObservableIterator.cs:line 42
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at OpenRasta.Codecs.CodecExtensions.TryAssignKeyValues(ICodec codec, IHttpEntity entity, IObjectBinder binder, Action`1 assigned, Action`1 failed) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Codecs\CodecExtensions.cs:line 36
   at OpenRasta.Codecs.CodecExtensions.<>c__DisplayClassb.<TryAssignKeyValues>b__a(Boolean result, IObjectBinder binder) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Codecs\CodecExtensions.cs:line 52
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at OpenRasta.Codecs.CodecExtensions.TryAssignKeyValues(ICodec codec, IHttpEntity entity, IEnumerable`1 binders, Action`1 assigned, Action`1 failed) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Codecs\CodecExtensions.cs:line 52
   at OpenRasta.OperationModel.Hydrators.RequestEntityReaderHydrator.TryAssignKeyedValues(IHttpEntity requestEntity, ICodec codec, Type codecType, IOperation operation) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\OperationModel\Hydrators\RequestEntityReaderHydrator.cs:line 88
   at OpenRasta.OperationModel.Hydrators.RequestEntityReaderHydrator.<Process>d__8.MoveNext() in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\OperationModel\Hydrators\RequestEntityReaderHydrator.cs:line 53
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OpenRasta.Pipeline.Contributors.AbstractOperationProcessing`2.ProcessOperations(ICommunicationContext context) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Pipeline\Contributors\AbstractOperationProcessing.cs:line 24
   at OpenRasta.Pipeline.PipelineRunner.ExecuteContributor(ICommunicationContext context, ContributorCall call) in c:\Projects\OpenRasta\openrasta-stable\src\core\OpenRasta\Pipeline\PipelineRunner.cs:line 187

**Comment by holytshirt** [comment]
Thanks @JornWildt, I will get that fixed. Thanks for the all the information :+1:

**Comment by holytshirt** [comment]
Hi @JornWildt  fix is done and pushed to Nuget  openrasta-core 2.5.54 
Can you confirm it has solved your issue so I can close it.
Thanks for your help!

**Comment by JornWildt** [comment]
That seems like a good solution. Thanks.
